### docker-compose.yml for external services. Run Tunnelmole itself outside of Docker with node.
services:
  tunnel:
    build: .
    image: altane/tunnelmole-service:latest
    environment:
      HTTP_PORT: ${HTTP_PORT:-8000}
      WS_PORT: ${WS_PORT:-8080}
      DOMAINE: ${DOMAINE:-localhost}
      TUNNEL_PASSWORD: ${TUNNEL_PASSWORD:-password}
      ENVIRONMENT: ${ENVIRONMENT:-local}
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_HOST: ${MYSQL_HOST:-localhost}
      DB_NAME: ${DB_NAME:-tunnelmole}
      NODE_ENV: production
    ports:
      - 80:${HTTP_PORT}
      - 81:${WS_PORT}

  mysql:
    image: mysql:8.0.32
    container_name: mysql-8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-password}
    ports:
      - "3306:3306"